# Generated by Django 5.0.1 on 2024-06-23 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iladia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nailsimages',
            old_name='client',
            new_name='client_id',
        ),
    ]
