# Generated by Django 5.0.1 on 2024-06-23 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iladia', '0002_rename_client_nailsimages_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nailsimages',
            old_name='client_id',
            new_name='client',
        ),
    ]
