# Generated by Django 5.0.1 on 2024-06-23 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iladia', '0005_nailsimages_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nailsimages',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iladia.nailsclients'),
        ),
    ]
