# Generated by Django 5.0.1 on 2024-06-23 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iladia', '0007_remove_tattooimages_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='tattooimages',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iladia.tattooclients'),
            preserve_default=False,
        ),
    ]
